env:
  TZ: "Asia/Hong_Kong"
  LANG: "C.UTF-8"
  LC_ALL: "C"
  
  # Kernel
  DEVICE_CODENAME: "a21s"
  BUILD_USER: "lua"
  BUILD_HOST: "arch"
  KERNEL_SOURCE: "https://github.com/sqldown/atlas.git"
  KERNEL_BRANCH: "master"
  DEVICE_DEFCONFIG: "exynos850-a21snsxx_defconfig"
  ANYKERNEL: "https://github.com/greenforce-project/AnyKernel3"
  
  # Telegram Encrypted Secrets
  TG_TOKEN: "ENCRYPTED[!9edcd3081be002db985bb813ca9d803aef002564bcca2a513a4b35e96374c1c5dd11ba6fb118abf024f61db4babc334a!]"
  TG_CHAT_ID: "ENCRYPTED[!693f768ca576838abbb036f8efd169321f2a7f8c2d10a43ecfd74048c66b538a8eda467cf205630b31e60b7023a224bd!]"

  # Toolchain Configuration
  USE_CLANG: "greenforce" # "aosp" or "greenforce"
  CLANG_ROOTDIR: "/tmp/cirrus-ci-build/clang"
  AOSP_CLANG_URL: "https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86/+archive/603a89415bbb04dff8bc577b95534479ec13fdc5/clang-r574158.tar.gz"
  GREENFORCE_CLANG_URL: "https://github.com/greenforce-project/greenforce_clang/releases/download/20251012/gf-clang-22.0.0git-20251012.tar.gz"

  # Kernel Build Configuration
  TYPE_IMAGE: "Image.gz"
  BUILD_DTBO: "false"

  # Kernel SU configuration
  KERNELSU: "false"
  KERNELSU_TYPE: "sukisu"
  KERNELSU_BRANCH: "susfs-main"
  KPM_PATCH: "false"
  KPM_VERSION: "0.12.0"

  # Build optimization
  BUILD_OPTIONS: "-j8"
  CCACHE: "true"
  CCACHE_DIR: "/tmp/ccache"
  CCACHE_MAXSIZE: "2G"
  CCACHE_COMPRESS: "true"
  
  # New: Enhanced logging and debugging
  DEBUG_MODE: "false"
  KEEP_BUILD_LOGS: "true"

task:
  name: "Kernel Build"
  timeout_in: 3h
  container:
    image: mhmmdfdlyas/dockerfile:k-ubuntu
    cpu: 8
    memory: 32G

  # Cache configuration
  ccache_cache:
    folder: /tmp/ccache
    fingerprint_script: 
      - cat .cirrus.yml
      - echo "$AOSP_CLANG_URL"
      - echo "$GREENFORCE_CLANG_URL"
      - echo "$DEVICE_DEFCONFIG"

  update_script:
    - apt-get update
    - apt-get install -y aria2 ccache libssl-dev ncurses-dev flex bison cpio xz-utils locales libtinfo5
    - echo 'en_US.UTF-8 UTF-8' > /etc/locale.gen && /usr/sbin/locale-gen
    - ln -snf /usr/share/zoneinfo/"$TZ" /etc/localtime && echo "$TZ" > /etc/timezone
    - apt-get clean

  setup_script:
    - mkdir -p /tmp/ccache
    - ccache -M $CCACHE_MAXSIZE
    - ccache -z

  sync_script:
    - chmod +x download.sh
    - ./download.sh

  build_script:
    - chmod +x build.sh
    - ./build.sh

  cleanup_script:
    - chmod +x done.sh
    - ./done.sh
